// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnOtbmHLWUA9O3zfz2EutVk0CP0ULHWYA',
    appId: '1:816456164286:web:3c1c229b307d7c5f22cfef',
    messagingSenderId: '816456164286',
    projectId: 'groceries-comm-flutter',
    authDomain: 'groceries-comm-flutter.firebaseapp.com',
    storageBucket: 'groceries-comm-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjAM6KliZFOcz5utqDkJDdxjWIm9NNb-c',
    appId: '1:816456164286:android:e64533f074fd3d2522cfef',
    messagingSenderId: '816456164286',
    projectId: 'groceries-comm-flutter',
    storageBucket: 'groceries-comm-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeKU0o0z8wQHfJOSDh-2p6rHpLHL40npM',
    appId: '1:816456164286:ios:f293242a14fa741922cfef',
    messagingSenderId: '816456164286',
    projectId: 'groceries-comm-flutter',
    storageBucket: 'groceries-comm-flutter.appspot.com',
    iosBundleId: 'com.example.groceriesCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeKU0o0z8wQHfJOSDh-2p6rHpLHL40npM',
    appId: '1:816456164286:ios:f293242a14fa741922cfef',
    messagingSenderId: '816456164286',
    projectId: 'groceries-comm-flutter',
    storageBucket: 'groceries-comm-flutter.appspot.com',
    iosBundleId: 'com.example.groceriesCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnOtbmHLWUA9O3zfz2EutVk0CP0ULHWYA',
    appId: '1:816456164286:web:371ffdb8c5010a7822cfef',
    messagingSenderId: '816456164286',
    projectId: 'groceries-comm-flutter',
    authDomain: 'groceries-comm-flutter.firebaseapp.com',
    storageBucket: 'groceries-comm-flutter.appspot.com',
  );
}
